### ISSUE TITLE
[Question] Adding WebView2 browser in UnitedSets

### ISSUE THREAD

**Issue by GetGet99** [Windows-Apps-Hub/UnitedSets#15]
Will you consider it something useful, or will you consider it to be bloatware if we add the WebView2 browser in UnitedSets?

Please react to this post:
👍= Useful feature
👎= Bloatware

**Comment by Omegion2** [comment]
something useful feature.

**Comment by Get0457** [comment]
WebView2 browser will not directly be added to UnitedSets
