### ISSUE TITLE
[Feature Request] Hide Captured Windows from taskbar

### ISSUE THREAD

**Issue by No2515** [Windows-Apps-Hub/UnitedSets#25]
This allows less clutter if possible. Everything is already tidy with this program. Seems redundant to show in the Taskbar, especially when opening multiple windows.

**Comment by Get0457** [comment]
I think this is already the case, isn't it? Or maybe it is only on experimental preview. (link to install experimental preview version is in read me) I wasn't sure.
![image](https://user-images.githubusercontent.com/41405393/222894689-e48e58c0-2ac1-40fc-ae7c-b2c78a758055.png)

**Comment by Get0457** [comment]
Note that this only applies to non UWP window. See #2

**Comment by Get0457** [comment]
I'll keep the issue open for now in case you have any questions.

**Comment by No2515** [comment]
No, I downloaded via MS Store. If u have no plans to update the beta, I'll switch to dev version. 

But how would one switchback to beta from dev?

**Comment by GetGet99** [comment]
Anyways this is resolved, I think. Therefore,

I will close all the issues that are resolved in the code. I unfortunately don't have an ETA on when the store release will be here.
