### ISSUE TITLE
third window 

### ISSUE THREAD

**Issue by ajaywanekar** [Windows-Apps-Hub/UnitedSets#41]
after some time of adding the third window - using another window - later on even clicking on the third window the window doesn't pop up.

**Comment by Get0457** [comment]
It works for me. Are you using experimental release or the original one?

Maybe your third window is a UWP window (such as Windows Calculator, Photos, Settings, etc.) which really struggles on the original release.

If you are using the original release, you can try the experimental version by clicking on the experimental link in [Readme](https://github.com/FireCubeStudios/UnitedSets/blob/master/README.md) file (Experimental InDev Version one)

**Comment by Get0457** [comment]
Closed due to inactivity

**Comment by Get0457** [comment]
If you want to mention anything else, please open a new issue
