### ISSUE TITLE
[Bug] It broked the desktop

### ISSUE THREAD

**Issue by arduinoturkbatu** [Windows-Apps-Hub/UnitedSets#49]
So, I was testing app with clicking desktop icons. When I clicked into an icon with \<Tab\> key, it opened a blank window, and also the desktop is crashed. I solved the problem by closing the window and refreshing (F5) the desktop.
I think that's a problem that needs to be solved.

**Comment by Get0457** [comment]
Wow, it seems they changed the desktop class. I have added `WorkerW` to the blacklist and will come out next update.

**Comment by GetGet99** [comment]
I will close all the issues that are resolved in the code. I unfortunately don't have an ETA on when the store release will be here.
