### ISSUE TITLE
[Feature Request] Remember content

### ISSUE THREAD

**Issue by projectje** [Windows-Apps-Hub/UnitedSets#53]
Would be nice if I close and reopen the app that it brings back the applications that I tabbed.

Now I need to add the  same applications  each time again

**Comment by GetGet99** [comment]
Currently, I am trying to migrate that codebase up to the current version. This will take some time.

**Comment by GetGet99** [comment]
The PR #47 is merged. I'll have to figure out from here how to do that later

**Comment by GetGet99** [comment]
(accidentally close the issue so reopened)

**Comment by GetGet99** [comment]
Implemented
![image](https://github.com/Windows-Apps-Hub/UnitedSets/assets/41405393/3a791ffb-cdba-4532-9cd1-dd5752476f65)
- Limitations
  - Apps that only allow one process will not work correctly (ex. default Explorer option)
  - Inbox UWP/WinUI apps do not work

**Comment by GetGet99** [comment]
For limitation updates, please follow #64
